export const BASE = "anura_configs"
export const INFO_FILE = "info"
export const CONFIG_PREFIX = "conf_version_"
export const GENERAL_DATA = ".extra-config"
export const GLOBAL_CONFIG_JSON = "global_config.json"
